config/routes.rb
Rails.application.routes.draw do
  root "workers#index"
  resources :workers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/worker.rb
class Worker < ApplicationRecord
    validates :name,:date,:shift , presence: true
    before_create :check_for_name_and_date

    
    def check_for_name_and_date
        if Worker.find_by(name: self.name ,date: self.date)
            self.name = nil
            self.date = nil
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
	# http_basic_authenticate_with name: "admin", password: "admin", only: :destroy

	def index
		@workers = Worker.all
		# render json: @workers
	end

	def show 
		@worker = Worker.find(params[:id])
		# render json: @worker
	end

	def new
		@worker = Worker.new
		# render json: @worker
	end

	def create
		@worker = Worker.create(worker_params)
		if @worker.valid?
			redirect_to @worker
		else
			render :new, status: :unprocessable_entity
		end
	end

	def edit
		@worker = Worker.find(params[:id])
	end

	def update
		@worker = Worker.find(params[:id])
		if @worker.update(worker_params)
			redirect_to @worker
		else
			render :edit, status: :unprocessable_entity
		end
	end

	def destroy
		@worker = Worker.find(params[:id])
		@worker.destroy

		redirect_to root_path, status: :see_other
	end

	private

	def worker_params
		params.require(:worker).permit(:name,:shift,:date)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workplanning</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/workers/_form.html.erb
<%= form_with model: @worker do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>
  <% @worker.errors.full_messages_for(:name).each do |message| %>
    <div><%= message %></div>
  <% end %>

  <div>
    <%= form.label :shift %><br>
    <%= form.select :shift,["Shift-1[0-8]","Shift-2[8-16]","Shift-3[16-24]"] %>
  </div>
  <div>
    <%= form.label :date %><br>
    <%= form.date_field :date %>
  </div>
  <% @worker.errors.full_messages_for(:date).each do |message| %>
    <div><%= message %></div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/workers/edit.html.erb
<h1>Edit worker</h1>

<%= render "form" %>

app/views/workers/index.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="http://localhost:3000/">
      <img src="/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="30" height="24" class="d-inline-block align-text-top">
      Worker Details
    </a>
    <%= link_to "New Worker", new_worker_path%>
  </div>
  
</nav>
<hr>
<br>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Worker Name</th>
      <th scope="col">Shift</th>
      <th scope="col">Date</th>
    </tr>
  </thead>
  <tbody>
<% @workers.each do |worker| %>
    <tr>
    <%if worker.name != nil%>
      <th scope="row"><%= link_to worker.name.capitalize, worker %></th>
      <td><%= worker.shift%></td>
      <td><%= worker.date%></td>
      <%end%>
    </tr> 
<% end %>

</tbody>
</table>

app/views/workers/new.html.erb
<h1>New worker</h1>

<%= render "form"%>

app/views/workers/show.html.erb
<h1>Name:<%= @worker.name.capitalize %></h1>
<h1>Shift Timing :<%= @worker.shift %></h1>
<h1>Shift Date :<%= @worker.date %></h1>



<%= link_to "Edit", edit_worker_path(@worker) %>
<%= link_to "Delete" ,worker_path(@worker),data:{
                turbo_method: :delete,
                turbo_confirm: "Are you sure?"
      }%>